const VALIDATION = 602;
const WRONG_CREDENTIALS = 604;
const INVALID_ACTION = 605;
const PERMISSION_DENIED = 606;
const INVALID_DATA = 610;
const USERNAME = 'There is no matching username';

export {
    VALIDATION,
    WRONG_CREDENTIALS,
    INVALID_ACTION,
    PERMISSION_DENIED,
    INVALID_DATA,
    USERNAME
};